apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-wishlist
  name: mongo-wishlist-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-wishlist
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-wishlist
  labels:
    app: mongo-wishlist
spec:
  selector:
    matchLabels:
      app: mongo-wishlist
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-wishlist
      name: mongo-wishlist-service
    
    
    spec:
      containers:
        - image: mongo:latest
          name: mongo-wishlist
          
          ports:
            - containerPort: 27017
              name: mongo-wishlist      