apiVersion: v1
kind: Service
metadata:
  name: reddis-db-svc
spec:
  type: NodePort
  selector:
    app: reddis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
spec:
  type: NodePort
  selector:
    app: mongo-wishlist
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017