/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package br.com.brunooliveira.jaya.wishlistrestapi.service;

import br.com.brunooliveira.jaya.wishlistrestapi.dto.ProdutoDTO;
import br.com.brunooliveira.jaya.wishlistrestapi.dto.WishListDTO;

import org.springframework.http.ResponseEntity;

import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;




public interface WishlistService {

     Mono<ResponseEntity<Void>> deleteProduto(String requestId,String userId, String produtoId,   ServerWebExchange exchange) ;

    Mono<ResponseEntity<Void>> deleteCache(String requestId,String userId,   ServerWebExchange exchange) ;

    Mono<ResponseEntity<WishListDTO>> getWishListByUsuarioId(String requestId,String userId,   ServerWebExchange exchange) ;

      Mono<ResponseEntity<ProdutoDTO>> getProdutoByUsuarioIdAndProdutoId(String requestId, String userId, String produtoId, ServerWebExchange exchange);


      Mono<ResponseEntity<ProdutoDTO>> postProduto(String requestId,String userId, ProdutoDTO produtoDTO,   ServerWebExchange exchange) ;

}
